KeyError in line 9 of /beegfs/prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/src/snakefile:
'path_out'
  File "/beegfs/prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/src/snakefile", line 9, in <module>
srun: error: galatea: task 0: Exited with exit code 1
Building DAG of jobs...
Pulling singularity image docker://aminale/test:firstpush.
Using shell: /usr/bin/bash
Provided cores: 10
Rules claiming more threads will be scaled down.
Job stats:
job            count    min threads    max threads
-----------  -------  -------------  -------------
all                1              1              1
predict            2              1              1
train_model        1              1              1
total              4              1              1

Select jobs to execute...

[Thu Jul  7 18:41:08 2022]
rule train_model:
    input: /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/output/merged_training/annotation.csv, /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/output/merged_training/selected_ge.csv
    output: /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/output/merged_training/val_set.pkl, /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/output/merged_training/train_set.pkl, /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/output/merged_training/model_CC_GE.pkl, /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/output/merged_training/model_GE.pkl, /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/output/merged_training/model_CC.pkl
    jobid: 11
    resources: tmpdir=/tmp

python /beegfs/prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/src/.snakemake/scripts/tmpp_97gn0o.training.py
Activating singularity image /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/src/.snakemake/singularity/832e3cd54b08b0943b10d9357d10dace.simg
2022-07-07 18:41:14.001994: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.singularity.d/libs
2022-07-07 18:41:14.002047: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-07-07 18:41:19.987364: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.singularity.d/libs
2022-07-07 18:41:19.987443: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-07-07 18:41:19.987481: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: galatea
2022-07-07 18:41:19.987492: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: galatea
2022-07-07 18:41:19.987587: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: NOT_FOUND: was unable to find libcuda.so DSO loaded into this program
2022-07-07 18:41:19.987653: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 470.57.2
2022-07-07 18:41:19.987974: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
0
Epoch 0, loss 0.66, val_loss 0.69, accuracy 0.60, val_accuracy 0.67
Epoch 100, loss 0.21, val_loss 0.65, accuracy 0.92, val_accuracy 0.80
Epoch 0, loss 0.76, val_loss 0.72, accuracy 0.50, val_accuracy 0.47
Epoch 100, loss 0.32, val_loss 0.59, accuracy 0.89, val_accuracy 0.67
Epoch 200, loss 0.17, val_loss 0.65, accuracy 0.94, val_accuracy 0.67
Epoch 0, loss 0.69, val_loss 0.69, accuracy 0.52, val_accuracy 0.40
Traceback (most recent call last):
  File "/beegfs/prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/src/.snakemake/scripts/tmpp_97gn0o.training.py", line 197, in <module>
    model, history= training(model, train[:,dim_exp:(dim_exp+dim_cells)]
  File "/beegfs/prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/src/.snakemake/scripts/tmpp_97gn0o.training.py", line 88, in training
    history = model.fit(
  File "/opt/conda/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/conda/lib/python3.9/site-packages/h5py/_hl/files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/opt/conda/lib/python3.9/site-packages/h5py/_hl/files.py", line 232, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 126, in h5py.h5f.create
OSError: Unable to create file (file signature not found)
[Thu Jul  7 18:42:19 2022]
Error in rule train_model:
    jobid: 11
    output: /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/output/merged_training/val_set.pkl, /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/output/merged_training/train_set.pkl, /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/output/merged_training/model_CC_GE.pkl, /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/output/merged_training/model_GE.pkl, /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/output/merged_training/model_CC.pkl

RuleException:
CalledProcessError in line 98 of /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/src/snakefile:
Command ' singularity  exec --home /beegfs/prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/src -B /prj --bind /home/alemsara/miniconda3/lib/python3.9/site-packages:/mnt/snakemake /prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/src/.snakemake/singularity/832e3cd54b08b0943b10d9357d10dace.simg bash -c 'set -euo pipefail;  python /beegfs/prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/src/.snakemake/scripts/tmpp_97gn0o.training.py'' returned non-zero exit status 1.
  File "/prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/src/snakefile", line 98, in __rule_train_model
  File "/home/alemsara/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /beegfs/prj/NUM_CODEX_PLUS/Amina/CellSubmission/Prediction_scOmics/src/.snakemake/log/2022-07-07T184102.844867.snakemake.log
srun: error: galatea: task 0: Exited with exit code 1
